# Set node as the image
FROM node:16.14.2-alpine

# Set where the working directory is
WORKDIR /app

# Add dependency descriptions
COPY ./server/package.json /app
COPY ./server/package-lock.json /app

# install dependencies
RUN npm install

COPY ./server /app

# Start the node app
CMD ["node", "index.js"]